version: 2.1

executors:
  my-custom-executor:
    docker:
      - image: cimg/docker:stable  # Replaced 'u' with a valid Docker image
        auth:
          # Ensure you have first added these secrets
          # Visit app.circleci.com/settings/project/github/HyperCogWizard/WhatsApp-Business-API-Setup-Scripts/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD

jobs:
  build-and-push:
    executor: my-custom-executor
    working_directory: ~/project
    steps:
      - checkout

      - setup_remote_docker:
          version:
#          version: 20.10.8

      - run:
          name: Login to Docker Registry
          command: |
            echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USER --password-stdin

      - run:
          name: Build Docker Images
          command: |
            docker-compose -f docker-compose.yml build

      - run:
          name: Tag and Push Images
          command: |
            services=$(docker-compose -f docker-compose.yml config --services)
            for service in $services; do
              image_name="$DOCKER_HUB_USER/${service}:${CIRCLE_SHA1}"
              docker tag ${service} ${image_name}
              docker push ${image_name}
            done

      - persist_to_workspace:
          root: ~/project
          paths:
            - docker-compose.yml

  deploy:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - attach_workspace:
          at: ~/project

      - add_ssh_keys:
          fingerprints:
            - "YOUR_SSH_KEY_FINGERPRINT"  # Replace with your actual SSH key fingerprint

      - run:
          name: Deploy to On-Premise Server
          command: |
            ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST \<< 'EOF'
              cd /path/to/your/project
              git pull

              echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USER --password-stdin

              services=$(docker-compose config --services)
              for service in $services; do
                sed -i "s|image:.*|image: $DOCKER_HUB_USER/${service}:${CIRCLE_SHA1}|g" docker-compose.yml
              done

              docker-compose down
              docker-compose pull
              docker-compose up -d
            EOF

workflows:
  build-and-deploy:
    jobs:
      - build-and-push
      - deploy:
          requires:
            - build-and-push
          filters:
            branches:
              only: main  # Adjust to your deployment branch if different
